syntax on
source ~/.vim/config/config-normal
source ~/.vim/config/config-autopairs
source ~/.vim/config/config-cscope
source ~/.vim/config/config-pkg-manager
source ~/.vim/config/config-neocomplcache
"source ~/.vim/config/config-neosnippet
"source ~/.vim/config/config-clang-complete
"source ~/.vim/config/config-neocomplcache-clang
