(provide 'config-xcscope)

(add-to-list 'load-path "~/.emacs.d/elpa/xcscope-20140510.1437")
(require 'xcscope)
(cscope-setup)
(setq cscope-do-not-update-database t)
;;(define-key global-map [(f11)]  'cscope-set-initial-directory)
;;(define-key global-map [(f12)]  'cscope-unset-initial-directory)
;;(define-key global-map [(f3)]  'cscope-find-this-symbol)
;;(define-key global-map [(control f3)]  'cscope-next-symbol)
;;(define-key global-map [(meta f3)] 'cscope-prev-symbol)
;;(define-key global-map [(f4)]  'cscope-find-global-definition-no-prompting)
;;(define-key global-map [(control f4)]  'cscope-pop-mark)
;;(define-key global-map [(f5)]  'cscope-find-this-file)
;;(define-key global-map [(control f5)] 'cscope-next-file)
;;(define-key global-map [(meta f5)] 'cscope-prev-file)
;;(define-key global-map [(f6)] 'cscope-find-functions-calling-this-function)
;;(define-key global-map [(control f6)] 'cscope-find-called-functions)
;;(define-key global-map [(f7)] 'cscope-find-this-text-string)
;;(define-key global-map [(control f7)] 'cscope-find-egrep-pattern)
;;(define-key global-map [(f9)]    'cscope-display-buffer-toggle)

